/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_jnitest_ndk_test_NDKTest2 */

#ifndef _Included_com_example_administrator_jnitest_ndk_test_NDKTest2
#define _Included_com_example_administrator_jnitest_ndk_test_NDKTest2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_jnitest_ndk_test_NDKTest2
 * Method:    getStringFromNativeTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_jnitest_ndk_test_NDKTest2_getStringFromNativeTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
